### ISSUE TITLE
lack of filter_with_inception.py file

### ISSUE THREAD

**Issue by XinyaChen21** [snap-research/3dgp#3]
Thanks so much for this inspiring and excellent work in generating 3D representations from non-aligned 2D inputs!
I found the file "scripts/data_scripts/filter_with_inception.py" is not in the repo. Could you release the file?

**Comment by universome** [comment]
Hi @XinyaChen21 
Sorry, the script name is `run_instance_selction.py`, not `filter_with_inception.py`, I fixed the name, thank you!
